version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.10.3-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: ml1239/bot_demo:v1.0
    expose: [5055]
